baseUrl = "https://adracea.github.io/"

[params]
  color = "orange"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Welcome to my personal homepage!"
  keywords = "homepage, blog"
  images = [""]

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/rhazdon/hugo-theme-hello-friend-ng'
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/posts"
