baseUrl = "https://adracea.github.io/"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
title = "drakkarson@home"
googleAnalytics = 'G-Y3S54PW700'
enableGitInfo   = false
enableEmoji     = true
staticDir = ['static']
# justifyContent = false 
[author]
  name = "Alexandru Dracea"
[params]
  # color = "orange"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Welcome to my personal homepage!"
  # [params.favicon.color]
  #   mask = "#1b1c1d"
  #   msapplication = "#1b1c1d"
  #   theme = "#1b1c1d"

  # [params.logo]
  #   logoMark     = ">"
  #   logoText     = "$ cd /home/"
  #   logoHomeLink = "/"
  # Set disableReadOtherLogs to true in order to hide the links to other logs.
  disableReadOtherLogs = false
  enableThemeToggle = true
  # Enable sharing buttons, if you like
  enableSharingButtons = true
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false
  themeColor = "orange"
  [params.portrait]
    path     = "https://avatars.githubusercontent.com/u/6214663?v=4"
    alt      = "Portrait"
    maxWidth = "150px"
      [[params.social]]
    name = "github"
    url  = "https://github.com/adracea"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/alexandru-marin-dracea-910b51122/"
  # Metadata mostly used in document's head
  description = "Welcome to my personal homepage!"
  keywords = "homepage, log"
  [params.logo]
    logoMark     = "⚡"
    logoText2     = "$"
    logoText     = "admin@drakkarson.com>/drakkarson/home/"
    logoHomeLink = "/" 
    logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#cf3d04"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    logoCursorPathname = true
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"
  images = [""]

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"
  # logs = "logs"
[menu]
  [[menu.main]]
    identifier = "about"
    name       = ">$ file drakkarson"
    url        = "/about/"
[[menu.main]]
  identifier = "logs"
  name       = ">$ cd /logs"
  url        = "/logs/"
[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/adracea/hugo-theme-hello-friend-ng'
  