baseUrl = "https://adracea.github.io/"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
title = "drakkarson@home"
staticDir = ['static']
[author]
  name = "Alexandru Dracea"
[params]
  # color = "orange"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Welcome to my personal homepage!"
  # [params.favicon.color]
  #   mask = "#1b1c1d"
  #   msapplication = "#1b1c1d"
  #   theme = "#1b1c1d"

  # [params.logo]
  #   logoMark     = ">"
  #   logoText     = "$ cd /home/"
  #   logoHomeLink = "/"
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false
  enableThemeToggle = true
  # Enable sharing buttons, if you like
  enableSharingButtons = true
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true
  [params.portrait]
    path     = "https://avatars.githubusercontent.com/u/6214663?v=4"
    alt      = "Portrait"
    maxWidth = "150px"
      [[params.social]]
    name = "github"
    url  = "https://github.com/adracea"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/alexandru-marin-dracea-910b51122/"
  # Metadata mostly used in document's head
  description = "Welcome to my personal homepage!"
  keywords = "homepage, blog"
  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd ~"
    logoHomeLink = "/"
  images = ["/static/favicon.ico"]

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"
[[menu.main]]
  identifier = "blog"
  name       = ">$ cd /blog"
  url        = "/posts"
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/adracea/hugo-theme-hello-friend-ng'